api:
    resource: "@AppBundle/Controller/ArticlesController.php"
    type:     rest
    prefix:   api

front:
    resource: "@AppBundle/Controller/FrontController.php"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   doc
